logoutput: stderr

internal: @AETHERCLOUD_INTERNAL_IPV4@ port = 1080
internal: @AETHERCLOUD_INTERNAL_IPV6@ port = 1080
external: @AETHERCLOUD_IPV6@

socksmethod: username
clientmethod: none

user.privileged: root
user.unprivileged: proxy

timeout.negotiate: 30
timeout.io: 0

client pass {
  from: 0.0.0.0/0 to: 0.0.0.0/0
  log: error
}

client pass {
  from: ::/0 to: ::/0
  log: error
}

socks pass {
  from: 0.0.0.0/0 to: ::/0
  command: connect udpassociate
  protocol: tcp udp
  log: error
}

socks pass {
  from: ::/0 to: 0.0.0.0/0
  command: bindreply udpreply
  protocol: tcp udp
  log: error
}

socks pass {
  from: ::/0 to: ::/0
  command: connect udpassociate bindreply udpreply
  protocol: tcp udp
  log: error
}
